{% set name = "jaxlie" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxlie-{{ version }}.tar.gz
  sha256: bf2c2bbfdb66d3063464cc0e3bd9e20c80b0593e8488ea277edb14e59713aa62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jax >=0.2.14
    - jaxlib >=0.1.67
    - jax-dataclasses >=1.4.4
    - numpy
    - overrides !=4
    - tyro

test:
  imports:
    - jaxlie
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: http://github.com/brentyi/jaxlie
  summary: Matrix Lie groups in JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
